import javax.swing.JOptionPane;
/**
 *
 * @author deepr
 */
public class LoginUI extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    private DisplayManager HeadMgr;
    private UserManager UM;
    public LoginUI(DisplayManager ob,UserManager ob1) {
        initComponents();
        ProjTitle.setVisible(false);
        credits.setVisible(false);
        HeadMgr = ob;
        UM = ob1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        UID = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PWD = new javax.swing.JPasswordField();
        regICON = new javax.swing.JLabel();
        jLabelICON = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();
        ProjTitle = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        UID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        UID.setForeground(new java.awt.Color(102, 102, 102));
        UID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(UID);
        UID.setBounds(460, 210, 269, 26);

        loginBtn.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        jPanel2.add(loginBtn);
        loginBtn.setBounds(530, 320, 112, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        jLabel1.setText("Don't have an account ? ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(350, 430, 156, 34);

        regBtn.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        regBtn.setText("REGISTER");
        regBtn.setActionCommand("Register");
        regBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regBtnMouseClicked(evt);
            }
        });
        jPanel2.add(regBtn);
        regBtn.setBounds(530, 430, 140, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel2.setText("SIGN  IN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(460, 80, 180, 58);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Unique ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(340, 210, 92, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(340, 250, 92, 26);

        PWD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(PWD);
        PWD.setBounds(460, 250, 269, 26);

        regICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        jPanel2.add(regICON);
        regICON.setBounds(710, 420, 55, 50);

        jLabelICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/XSbook2.png"))); // NOI18N
        jLabelICON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelICONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelICONMouseExited(evt);
            }
        });
        jPanel2.add(jLabelICON);
        jLabelICON.setBounds(240, 10, 70, 70);

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pexels-lisa.jpg"))); // NOI18N
        jPanel2.add(jLabelBG);
        jLabelBG.setBounds(0, 0, 230, 540);

        ProjTitle.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ProjTitle.setText("STUDENT RESOURCE MANAGEMENT");
        jPanel2.add(ProjTitle);
        ProjTitle.setBounds(320, 20, 260, 17);

        credits.setText("Made with ❤ by Xsociety");
        jPanel2.add(credits);
        credits.setBounds(320, 40, 240, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regBtnMouseClicked
        this.dispose();
        HeadMgr.dispRegisterUI();
    }//GEN-LAST:event_regBtnMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        // TODO add your handling code here:
        if(UID.getText().isEmpty() && PWD.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Field(s) Empty","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            User logged_in_user = UM.checkUser(UID.getText(),PWD.getText());
            if(logged_in_user != null){
                this.dispose();
                HeadMgr.setUser(logged_in_user);
                HeadMgr.dispDashboardUI();
            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong Credentials","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginBtnMouseClicked

    private void jLabelICONMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelICONMouseEntered
        // TODO add your handling code here:
        ProjTitle.setVisible(true);
        credits.setVisible(true);
    }//GEN-LAST:event_jLabelICONMouseEntered

    private void jLabelICONMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelICONMouseExited
        // TODO add your handling code here:
        ProjTitle.setVisible(false);
        credits.setVisible(false);
    }//GEN-LAST:event_jLabelICONMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI(new DisplayManager(),null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PWD;
    private javax.swing.JLabel ProjTitle;
    private javax.swing.JTextField UID;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelICON;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JLabel regICON;
    // End of variables declaration//GEN-END:variables
}
