
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deepr
 */
public class RegisterUI extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    private UserManager UserMgr;
    private DisplayManager HeadMgr;
    public RegisterUI(DisplayManager ob,UserManager ob1) {
        HeadMgr = ob;
        UserMgr = ob1;
        JFrame frame = new JFrame();
        frame.setSize(950, 460);
        initComponents();
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        cpass = new javax.swing.JTextField();
        emailTX = new javax.swing.JTextField();
        cno = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        deptCB = new javax.swing.JComboBox<String>();
        yearCB = new javax.swing.JComboBox<String>();
        jLabel18 = new javax.swing.JLabel();
        rulesBtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Confirm Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(950, 460));
        setPreferredSize(new java.awt.Dimension(950, 460));
        setSize(new java.awt.Dimension(950, 460));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 490));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIGN UP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(39, 27, 217, 45);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Unique ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(39, 105, 124, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(39, 181, 124, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Year");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 100, 60, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Contact Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(551, 254, 153, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(36, 254, 165, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Dept.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 100, 133, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Email id");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(551, 170, 133, 23);

        uid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uidKeyReleased(evt);
            }
        });
        jPanel1.add(uid);
        uid.setBounds(263, 103, 165, 23);

        pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });
        jPanel1.add(pass);
        pass.setBounds(263, 181, 165, 23);

        cpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpassKeyReleased(evt);
            }
        });
        jPanel1.add(cpass);
        cpass.setBounds(263, 254, 165, 23);

        emailTX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        emailTX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTXKeyReleased(evt);
            }
        });
        jPanel1.add(emailTX);
        emailTX.setBounds(722, 172, 161, 25);

        cno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnoKeyReleased(evt);
            }
        });
        jPanel1.add(cno);
        cno.setBounds(722, 256, 161, 25);

        registerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registerBtn.setText("REGISTER");
        registerBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn);
        registerBtn.setBounds(735, 340, 140, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("Already have an account?");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 15, 185, 17);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("GO BACK AND SIGN IN ");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(680, 13, 210, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(263, 157, 165, 0);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel12);
        jLabel12.setBounds(264, 433, 164, 0);

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(263, 211, 165, 15);

        jLabel14.setBackground(new java.awt.Color(0, 204, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(722, 354, 161, 0);

        jLabel15.setBackground(new java.awt.Color(0, 204, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(722, 233, 161, 0);

        jLabel16.setBackground(new java.awt.Color(0, 204, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(260, 330, 240, 30);

        jLabel17.setBackground(new java.awt.Color(0, 204, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(722, 157, 161, 0);

        deptCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deptCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "ECE", "IT", "ME", "EEE", "EE" }));
        jPanel1.add(deptCB);
        deptCB.setBounds(620, 100, 75, 28);

        yearCB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st", "2nd", "3rd", "4th" }));
        jPanel1.add(yearCB);
        yearCB.setBounds(800, 100, 80, 28);

        jLabel18.setBackground(new java.awt.Color(0, 204, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(jLabel18);
        jLabel18.setBounds(263, 326, 165, 0);

        rulesBtn.setText("RULES");
        rulesBtn.setToolTipText("");
        rulesBtn.setBorder(null);
        rulesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rulesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rulesBtnMouseExited(evt);
            }
        });
        jPanel1.add(rulesBtn);
        rulesBtn.setBounds(550, 360, 90, 30);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("• Be Respectful to others in the community\n");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 310, 310, 40);

        jLabel20.setText("• DO NOT use the platform for jobs unrelated to education");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 340, 380, 20);

        jLabel21.setText("• Contact Admin [Xsociety.admin@gmail.com] in case of urgent issues");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(40, 360, 440, 20);

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pexlorenzo.jpg"))); // NOI18N
        jLabelBG.setMinimumSize(new java.awt.Dimension(950, 460));
        jLabelBG.setName(""); // NOI18N
        jPanel1.add(jLabelBG);
        jLabelBG.setBounds(0, 0, 930, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 1, 930, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
        HeadMgr.dispLoginUI();
    }//GEN-LAST:event_jButton2MouseClicked

    private void uidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uidKeyReleased
        String patt1="^[0-9]{4,4}$";
        Pattern p1 = Pattern.compile(patt1);
        Matcher m=p1.matcher(uid.getText());
        if(!m.matches()){
            jLabel11.setText("Invalid unique id !");
        }
        else{
            jLabel11.setText(null);
        }   
    }//GEN-LAST:event_uidKeyReleased

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        String patt1="^[0-9a-zA-Z$&+,:;=\\\\\\\\?@#|/'<>.^*()%!-]{8,20}$";
        Pattern p1 = Pattern.compile(patt1);
        Matcher m=p1.matcher(pass.getText());
        if(!m.matches()){
            jLabel13.setText("Minimum 8 characters!");
        }
        else{
            jLabel13.setText(null);
        }   
    }//GEN-LAST:event_passKeyReleased

    private void cnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnoKeyReleased
        String patt1="^[0-9]{10,10}$";
        Pattern p1 = Pattern.compile(patt1);
        Matcher m=p1.matcher(cno.getText());
        if(!m.matches()){
            jLabel14.setText("Invalid contact no.!");
        }
        else{
            jLabel14.setText(null);
        }   
    }//GEN-LAST:event_cnoKeyReleased

    private void emailTXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTXKeyReleased
        String patt1="^[A-Za-z0-9]+[@]{1}+[a-z0-9]+[.]{1}+[a-z]+$";
        Pattern p1 = Pattern.compile(patt1);
        Matcher m=p1.matcher(emailTX.getText());
        if(!m.matches()){
            jLabel15.setText("Invalid email!");
        }
        else{
            jLabel15.setText(null);
        }   
    }//GEN-LAST:event_emailTXKeyReleased

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if((uid.getText().equals(""))||pass.getText().equals("")||cpass.getText().equals("")||emailTX.getText().equals("")||cno.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Field(s) Empty","FAILED",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_registerBtnActionPerformed
        else{
            UserMgr.init();
            User chk = UserMgr.searchUser(uid.getText());
            if(chk != null){
                JOptionPane.showMessageDialog(null,"User already Exists","Status",JOptionPane.ERROR_MESSAGE);
            }
            else{
            User new_user = new User(uid.getText(),pass.getText(),yearCB.getItemAt(deptCB.getSelectedIndex()),deptCB.getItemAt(deptCB.getSelectedIndex()),emailTX.getText(),cno.getText());
            
            //System.out.println(new_user.toString());
            
            if(UserMgr.register(new_user))
                JOptionPane.showMessageDialog(null,"REGISTRATION SUCCESSFULL","Status",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                HeadMgr.dispLoginUI();
            }
        }}
    private void cpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpassKeyReleased
       String password =new String(pass.getText());
       String conpassword = new String(cpass.getText());
       if(password.compareTo(conpassword)!=0){
           jLabel16.setText("Passwords don't match");
       }
       else{
           jLabel16.setText("");
       }
    }//GEN-LAST:event_cpassKeyReleased

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
      
    }//GEN-LAST:event_cpassActionPerformed

    private void rulesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rulesBtnMouseEntered
        // TODO add your handling code here:
        jLabel19.setVisible(true);
        jLabel20.setVisible(true);
        jLabel21.setVisible(true);
    }//GEN-LAST:event_rulesBtnMouseEntered

    private void rulesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rulesBtnMouseExited
        // TODO add your handling code here:
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
    }//GEN-LAST:event_rulesBtnMouseExited
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUI(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cno;
    private javax.swing.JTextField cpass;
    private javax.swing.JComboBox<String> deptCB;
    private javax.swing.JTextField emailTX;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton rulesBtn;
    private javax.swing.JTextField uid;
    private javax.swing.JComboBox<String> yearCB;
    // End of variables declaration//GEN-END:variables
}
